<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Archiver.Application">
      <HintPath>..\Archiver.Application\bin\$(Configuration)\net8.0\Archiver.Application.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <Target Name="BuildApplicationProject" BeforeTargets="ResolveReferences">
    <MSBuild
      Projects="..\Archiver.Application\Archiver.Application.csproj"
      Targets="Build"
      Properties="Configuration=$(Configuration);RunAnalyzers=false" />
  </Target>
</Project>
